# If you want to add any module, you need to run:
# conda env update --file environment.yml --prune
# after adding it

name: GCM-RCM
channels:
  - conda-forge
dependencies:
  - python=3.12
  - netcdf4=1.7.2
  - numpy=2.2.6
  - xarray=2025.4.0
  - cdo=2.4.4
  - scipy=1.15.2
  - dask=2025.5.1
  - requests=2.32.4
  - matplotlib=3.10.3
  - plotly=6.2.0
  - esgf-pyclient=0.3.1
  - pip=25.1.1
  - pip:
      - cdsapi==0.7.6
    #  - esgpull==0.9.0